### ISSUE TITLE
logo missing  in readme

### ISSUE THREAD

**Issue by eneajaho** [ngxtension/ngxtension-platform#126]

**Comment by JeevanMahesha** [comment]
@eneajaho  this is fixed can we close this issue

**Comment by eneajaho** [comment]
We need new Logo to follow new angular logo guidelines 😄

**Comment by ajitzero** [comment]
Here you go 😆 

![image](https://github.com/nartc/ngxtension-platform/assets/19947758/252df5b0-5b70-4aa5-8490-2d725d02f114)
