### ISSUE TITLE
injectQueryParams (key) has incorrect type

### ISSUE THREAD

**Issue by james-schwartzkopf** [ngxtension/ngxtension-platform#325]
injectQueryParams(key) says it returns Signal<string | null> but could also return an array of strings.

I would suggest changing the current version to return the first string in the array if it's an array.  That would keep it compatible with what people are expecting,  Maybe add an optional flag that would force it to an array if it's a single string.  Similar to getAll on ParamMap.

**Comment by Dafnik** [comment]
This should be solved by #232

**Comment by Dafnik** [comment]
Can you confirm if it's fixed?

**Comment by Dafnik** [comment]
I thin this can also be closed! @eneajaho
