### ISSUE TITLE
computedFrom and computedAsync have been renamed without a major version bump

### ISSUE THREAD

**Issue by FabienDehopre** [ngxtension/ngxtension-platform#341]
Recently (in version 2.3.0), both `computedFrom` and `computedAsync` have been renamed respectively to `derivedFrom` and `derivedAsync` (via the PR #303).
I believe it should have been published as a major version (3.0.0) because it is a breaking change from the previous version 2.2.1

I know that a migration schematics has been released with the change to allow to update the code automatically but, nevertheless, I don't think it is sufficient to not bump the version to 3.0.0

I have a library that uses the `computedAsync` function and reference ngxtension package with the version range ^2.2.1 which includes 2.3.0. When I updated the library in my project the build and tests failed because the `ngxtension/computed-from` entry point does not exist anymore.

**Comment by eneajaho** [comment]
Hello @FabienDehopre 
Thanks for this issue. 

I believe this https://github.com/ngxtension/ngxtension-platform/pull/342 should fix the issue.

**Comment by eneajaho** [comment]
Hello @FabienDehopre 
We released a new patch https://github.com/ngxtension/ngxtension-platform/releases/tag/2.3.1 where we deprecate the functions which should solve the issue and also released a new major (v3.0.1) which removes the deprecated and fixes also the ng-update migrations. 

Thanks for opening this issue. 

Closing it now as it's complete.
