### ISSUE TITLE
Package "ngxtension" has a missing peer dependency of "@use-gesture/vanilla" @ "^10.0.0".

### ISSUE THREAD

**Issue by kle-pra** [ngxtension/ngxtension-platform#348]
I noticed this warning when running update script and am opening just in case it needs some attention. 

We are not using gestures so it doesn't seem to affect us but would you still recommend installing this as a dependency when using ngxtension version. 3.x?

**Comment by eneajaho** [comment]
Hello @kle-pra .
That's an optional dependency. You don't need to install it. 

@nartc 
Should we add optional to it? 

https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta

```json
"peerDependenciesMeta": {
    "@use-gesture/vanilla": {
      "optional": true
    }
  }
```

**Comment by sysmat** [comment]
I think if project dos not use gesture it is misleading, I'm in favor of optional

**Comment by kle-pra** [comment]
Thanks @eneajaho for explanation and suggestion, I also support optional.
