### ISSUE TITLE
[Inject Migration Enhancement]: Add ES Private Field notation support

### ISSUE THREAD

**Issue by ilirbeqirii** [ngxtension/ngxtension-platform#377]
When migrating from constructor-based to inject-based DI, add a new option, hence enhancement, to replace the TS `private` access modifier with ES `#private` fields.

**Comment by exequiel09** [comment]
I don't recommend using private fields when you have users using Safari < 16.4. See https://riegler.fr/blog/2024-05-17-private-fields-downleveling/

**Comment by ilirbeqirii** [comment]
This issue’s purpose is to add that new feature to the schematic, its on the user if he decides to support them during conversion or not. 

Article you shared, its a really good one but I think it should not stop us from having this feature supported.

For the warning, I will discuss it with maintainers 🙌
