### ISSUE TITLE
Migration schematics error in angular 18 

### ISSUE THREAD

**Issue by rssaranece94** [ngxtension/ngxtension-platform#390]
Hi,

I have angular 18, trying to run output and query migration, its telling its available in 17.1 or 17.3 + versions but project having v18.
`[ngxtension] output() is only available in v17.3 and later`
![ngxtension](https://github.com/ngxtension/ngxtension-platform/assets/20339805/4d5a69b1-a6bc-413d-a997-7987501c8f43)

**Comment by Dafnik** [comment]
Should be fixed with #388.

**Comment by eneajaho** [comment]
Waiting for the next release.

**Comment by eneajaho** [comment]
Fixed in https://github.com/ngxtension/ngxtension-platform/releases/tag/3.3.0
