### ISSUE TITLE
(bug) Press Kit images not found

### ISSUE THREAD

**Issue by jdegand** [ngxtension/ngxtension-platform#411]
#407 recently updated the file paths.  `.png` was used on lines 9 & 10  (all the logos are `.svg`).  This may contribute to the problem.

**Comment by michael-small** [comment]
Good catch with the `.png` in that PR. I copied it over from the other `index.mdx` blindly. However, it seems that flipping between dark theme and light theme doesn't change it to `ngxt-white` for the `dark` theme from what I can tell building it locally with the the `.svg` paths.

That `.png` copy over isn't related to why the press kit though. I'm not sure why the press kit images are still not loading, as it worked locally after I changed it and lodged PR 407.

**Comment by jdegand** [comment]
If it is related to themes, I ran into similar problems before with `astro`.  The `Auto` setting causes problems with conditionals.

**Comment by jdegand** [comment]
I don't think dark mode has anything to do with this.  

Got `Files in the public directory are served at the root path` warning when I ran the docs with `pnpm run dev` inside `/docs` folder.  But if you remove `public` from `index.mdx`, the docs fail to compile.  I think you can delete `public` from the image path inside `logos.md` and maybe that might work.
