### ISSUE TITLE
add session and localstorage helper fn

### ISSUE THREAD

**Issue by tomalaforge** [ngxtension/ngxtension-platform#42]
I'm always copy pasting sessionstorage and localstorage get/save/remove function in all my project. 

Maybe adding them here can be a nice addon.

**Comment by eneajaho** [comment]
@tomalaforge Can you give more details please? maybe some code ?

**Comment by tomalaforge** [comment]
```ts
export type LocalStorageKey = '' // that's the issue, the best is to set up this key for your personal project to be more typesafe

export const localStorageSave = <T>(key: LocalStorageKey, data: T): void => {
  localStorage.setItem(key, JSON.stringify(data));
};

export const localStorageGet = <T>(key: LocalStorageKey): T | null => {
  const data = localStorage.getItem(key);
  return data && JSON.parse(data);
};

export const localStorageRemove = (key: LocalStorageKey): void => {
  localStorage.removeItem(key);
};
```

**Comment by tomer953** [comment]
Imo localstorage should be a service, something like

```ts
export class LocalStorageService {

  setItem<T>(key: string, value: T): void {
    localStorage.setItem(key, JSON.stringify(value));
  }

  getItem<T>(key: string): T | null {
    const storedValue = localStorage.getItem(key);
    if (storedValue === null) return null;
    return JSON.parse(storedValue) as T;
  }

  removeItem(key: string): void {
    localStorage.removeItem(key);
  }

  clear(): void {
    localStorage.clear();
  }
}
```

Then, Maybe `injectLocalStorage()` should return an instance of this service

**Comment by nartc** [comment]
Maybe we can take it a step further and have a Signal-based + Zod-powered Storage instead? https://twitter.com/Nartc1410/status/1643474376199663621

**Comment by tomalaforge** [comment]
Seems nice, but is adding another dependancy a good idea ? most projects don't use Zod and we rely on zod to use this service.

**Comment by nartc** [comment]
@tomalaforge since it's in a secondary entry point, it'll only be required if the consumers use `ngxtension/storage` (imaginary name). But it makes sense to **NOT** rely on 3rd party lib as well.

**Comment by wanoo21** [comment]
I would change it a bit, making it more dynamically:

```ts
export const [injectStorage, provideStorage] = createInjectionToken((): localStorage | sessionStorage => localStorage);

@Injectable({
 providedIn: 'root'
})
export class StorageService {

  const store = injectStorage()

  setItem<T>(key: string, value: T): void {
    store.setItem(key, JSON.stringify(value));
  }

  getItem<T>(key: string): T | null {
    const storedValue = store.getItem(key);
    if (storedValue === null) return null;
    return JSON.parse(storedValue) as T;
  }

  removeItem(key: string): void {
    store.removeItem(key);
  }

  clear(): void {
    store.clear();
  }
}
```

This way we can use either `localStorage` or `sessionStorage`. Or we can go even further, adding support of `cookie` as well.

Code not tested 🤷🏻‍♂️

**Comment by ducin** [comment]
IMO it's not a good idea to declare via generic T what local-storage-get should return, as:
- it's not type safe, it's just your declaration which is not verified
- wrapping it with either type guard or an assertion function seems a must have if, for any reason, the serialized structure might evolve within time
- not sure if that fits to an angular specific library, as it's not really angular specific.

`zod` is indeed a dependency on the other hand. How about accepting a function which runs the type guard, whatever the function is?

**Comment by eneajaho** [comment]
Can we also have any event when storage state changes?
