### ISSUE TITLE
`whenDocumentVisible` is not exported from `ngxtension/when-document-visible` entry point

### ISSUE THREAD

**Issue by FabienDehopre** [ngxtension/ngxtension-platform#424]
I forgot to export the `whenDocumentVisible` operator from the entry point. :(
I'll provide a PR as soon as possible.

**Comment by FabienDehopre** [comment]
@nartc or @eneajaho Sorry to bother you but this bug is important because the RxJS `whenDocumentVisible` operator is not exported from the entrypoint `ngxtension/when-document-visible` which makes it impossible to use.
I know it's my fault because I forgot to check the `index.ts` file before subimiting the initial implementation.
However, the PR that fixes the bug is ready since last week.
I would really appreciate if one of you (or any other code owner) can review the PR.
Thanks in advance.

**Comment by eneajaho** [comment]
Merged your fix. Thanks 🙏

**Comment by FabienDehopre** [comment]
@sysmat I believe that the fix has not been released yet.

**Comment by sysmat** [comment]
any progress?

**Comment by FabienDehopre** [comment]
@nartc any idea when you can release this fix?

**Comment by sysmat** [comment]
any progress

**Comment by eneajaho** [comment]
Sorry for delay. Released here https://github.com/ngxtension/ngxtension-platform/releases/tag/4.0.0
