### ISSUE TITLE
New Migration: Route LoadComponent

### ISSUE THREAD

**Issue by timdeschryver** [ngxtension/ngxtension-platform#445]
Would it be useful to add a migration to migrate routes using `component` to `loadComponent`?
If you want (and think this is helpful), I can write this migrator.

For example:

BEFORE:

```ts
import { Routes } from '@angular/router';
import { MenuListComponent } from './menu-list/menu-list.component';

export const MenuRoutes: Routes = [
  {
    path: 'menu',
    component: MenuListComponent
  },
];
```

AFTER MIGRATION:

```ts
import { Routes } from '@angular/router';
import { MenuListComponent } from './menu-list/menu-list.component';

export const MenuRoutes: Routes = [
  {
    path: 'menu',
    loadComponent: () => import('./menu-list/menu-list.component').then((c) => c.MenuListComponent)
  },
];
```

**Comment by eneajaho** [comment]
LOL, I'm working on that one exactly, but now directly inside the angular repo https://github.com/angular/angular/pull/56428

**Comment by timdeschryver** [comment]
Oops 😂!
I like that it's can be included within the Angular repo.

If it helps, I've already written the migrator within this library to run it locally - that was easier than updating each instance manually. I'll drop it here, maybe that it can be of help.

https://github.com/ngxtension/ngxtension-platform/compare/main...timdeschryver:migration/load-component?expand=1

**Comment by eneajaho** [comment]
> Oops 😂! I like that it's can be included within the Angular repo.
> 
> If it helps, I've already written the migrator within this library to run it locally - that was easier than updating each instance manually. I'll drop it here, maybe that it can be of help.
> 
> https://github.com/ngxtension/ngxtension-platform/compare/main...timdeschryver:migration/load-component?expand=1

Thanks, will make sure to support what you had as usecases 🙌
