### ISSUE TITLE
How can I handle HTTP calls with signals using ngxtension instead of subscribe?

### ISSUE THREAD

**Issue by jon9090** [ngxtension/ngxtension-platform#449]
I have a code snippet where I use `forkJoin` to subscribe to two HTTP calls within a function that's triggered by a click event.

Does `ngxtension` provide a way to handle this with signals instead of using `subscribe`? I tried `derivedAsync`, but it doesn't accept parameters.

```typescript
openUserDialog(userId: number) {
  forkJoin([
    this.http.get(`/api/user/${userId}/basic-info`), 
    this.http.get(`/api/user/${userId}/details`)
  ]).subscribe(async ([basicInfo, moreDetails]) => {
    const dialogRef = await this.dialog.open(...);
    dialogRef.componentInstance.basicInfo = basicInfo;
    dialogRef.componentInstance.moreDetails = moreDetails;
    ...
  });
}
```

**Comment by jdegand** [comment]
Signals are not really a replacement for RxJS and HTTP methods.  To make your API request more reactive, you should replace `forkJoin` with `combineLatest`.  `combineLatest` will listen to a given stream all the time until you destroy it.

**Comment by BDLB** [comment]
Hi @jon9090 ,

**Comment by BDLB** [comment]
Hi @jon9090,
Why do you need a signal instead of subscribe? Do you wish to not proceed new GET APIs for every openUserDialog function call?

**Comment by eneajaho** [comment]
Hello @jon9090 
For your usecase I'd use the createEffect utility https://ngxtension.netlify.app/utilities/stores/create-effect/
It enables you to not subscribe anywhere anymore and easily handle race-conditions.

```ts
openUserDialog = createEffect<number>(
  concatMap(userId => {
    forkJoin([
        this.http.get(`/api/user/${userId}/basic-info`), 
        this.http.get(`/api/user/${userId}/details`)
      ]).pipe(tap(async ([basicInfo, moreDetails])) => {
          const dialogRef = await this.dialog.open(...);
          dialogRef.componentInstance.basicInfo = basicInfo;
          dialogRef.componentInstance.moreDetails = moreDetails;
       })
  })
);
```

Closing this issue as we already have an utility for this. Please let me know what do you think about this one.
