### ISSUE TITLE
4.0.0: computedPrevious Error: NG0950:

### ISSUE THREAD

**Issue by sysmat** [ngxtension/ngxtension-platform#454]
- when using

```typescript
user = input.required<User>();
userPrev = computedPrevious(this.user);
```

- error
Error: NG0950: Input is required but no value is available yet. Find more at https://angular.dev/errors/NG0950
    at inputValueFn (core.mjs:96:13)
    at ngxtension-computed-previous.mjs:39:34
    at untracked (core.mjs:37064:12)
    at computedPrevious (ngxtension-computed-previous.mjs:39:18)

**Comment by sysmat** [comment]
using ng: 18.1.0

**Comment by sysmat** [comment]
it is working fine with ng 18.1.0 and  "ngxtension": "^3.5.5",

**Comment by sysmat** [comment]
I don't know how to fix it in my code, @eneajaho  thx for info

**Comment by eneajaho** [comment]
You need to initialize the computed previous inside ngOnInit

**Comment by sysmat** [comment]
hm, but then is not declerative

**Comment by sysmat** [comment]
```typescript
user= input.required<User>();
userPrev: Signal<User>;

ngOnInit() {
    this.userArnesPrev = computedPrevious(this.user);   
  }
```

**Comment by MillerSvt** [comment]
> You need to initialize the computed previous inside ngOnInit

I disagree. I have a lot of effects, that depends to computedPrevious, and now all is failed. Effects should initialize on constructor. So I make [proposal](#590) to rethink `computedPrevious` utility.
