### ISSUE TITLE
input() migration removes other decorators from inputs

### ISSUE THREAD

**Issue by jsangmeister** [ngxtension/ngxtension-platform#458]
If you execute `ng g ngxtension:convert-signal-inputs` on the following code:
```
export class CheckboxComponent {
  @Input()
  @HostBinding('class.active')
  public active?: boolean;
}
```
the automatic migration removes the `@HostBinding()` decorator without any notice or warning. Result:
```
export class CheckboxComponent {
  public active = input<boolean>();
}
```
This leads to errors which are only caught in e2e tests, if at all, since the code will still compile without any problems.

**Comment by jsangmeister** [comment]
I just became aware that `@HostBinding` will no longer work with the input signal (since it does not evaluate the signal, but takes it directly as a value). Nevertheless, removing the decorator without any warning does not seem sensible, better to not migrate it at all then.

On another note, is there a way to combine the `hostBinding()` feature of ngxtension with input signals? Unfortunately, when doing `public active = hostBinding('class.active', input(false))`, the input does no longer get recognized by angular and the template which uses it fails to compile.

**Comment by eneajaho** [comment]
Hello @jsangmeister 
Thanks for opening this issue. This looks like a bug, so as you said, it's better if we don't migrate these usecases. 
So, I'm planning to skip migrating these and also add a comment that says why it was not migrated.

**Comment by jsangmeister** [comment]
Thanks, sounds good! Regarding my other question, are there plans to support `hostBinding` in combination with inputs or is that not trivial to do?

**Comment by eneajaho** [comment]
Regarding hostbinding, to be honest, I like doing it like this: 

```ts
@Component({
  host: {
    '[class.active]': 'active()'
  }
})
export class Cmp {
   active = input(false);
}
```
