### ISSUE TITLE
add docs for injectLocalStorage

### ISSUE THREAD

**Issue by eneajaho** [ngxtension/ngxtension-platform#464]
Looks like docs weren't added when the utility was created https://github.com/ngxtension/ngxtension-platform/blob/main/libs/ngxtension/inject-local-storage/src/inject-local-storage.ts

**Comment by eneajaho** [comment]
Docs here: https://ngxtension.netlify.app/utilities/injectors/inject-local-storage/

**Comment by sysmat** [comment]
docs are missing from where to import injectLocalStorage
