### ISSUE TITLE
[NgxControlValueAccessor] Expose ngControl in public API

### ISSUE THREAD

**Issue by elnipa** [ngxtension/ngxtension-platform#477]
I really love the simplicity of the `NgxControlValueAccessor`. However, the current API is very limited when we deal with a little bit more complex cases, e.g. adding standard validators to the controls that are always needed.

A very simple solution to expand the API a little bit would be bv making the ngControl property public for the API.

```typescript
  public readonly ngControl = inject(NgControl, {
    self: true,
    optional: true,
  });
```

This allows to do somewhat like

```typescript
  protected cva = inject<EtaControlValueAccessor<Color | undefined>>(
    EtaControlValueAccessor,
  );
  control = this.cva.ngControl?.control as FormControl;

  ngAfterViewInit(): void {
    this.control?.addValidators(createColorValidator(true));
    this.control?.updateValueAndValidity();
  }
```

and re-using the control as inner FormControl in Formfields, e.g.

```html
  <input
    matInput
    [formControl]="control"
  />
```

I even added some more functionality with

```typescript
  private readonly _events$ = this.ngControl?.control?.events ?? of();

  public readonly errors$ = toSignal(
    this._events$.pipe(
      filter((v) => v instanceof StatusChangeEvent),
      map((v) => (v as StatusChangeEvent).status),
      filter((v) => v !== 'PENDING'),
      map(() => this.ngControl?.errors),
    ),
  );

  public readonly valid$ = computed(() => this.errors$() === null);
```

allows to access the errors inside of the component

```html
  @if (cva.errors$()?.['required']) {
    <mat-error>Required</mat-error>
  }
```

Any thoughts about this? 
At least exposing the ngControl for the public API would be a big help. Currently I need to create/maintain a copy instead of using your lib class right away.

**Comment by eneajaho** [comment]
cc @RobbyRabbitman

**Comment by RobbyRabbitman** [comment]
Hello there,

I see no problem when `ngControl` is made public. However I wonder, if you are able to inject the `NgxControlValueAccessor` token, you are also _able_ to inject the `NgControl` token.

yeah, maybe we can add some basic features like a signal which represents the errors of the control based on its status. Does anyone know when/if angular will add signal apis into their forms api?

A different topic: The `NgxControlValueAccessor` was written some time ago. With the latest features of angular, some parts can be rewritten e.g. outputs with `outputFromObservable`, inputs with signal based inputs `input`. Should the implementation be up to date in that sense?

**Comment by jdegand** [comment]
Signals forms are on the roadmap and this [issue](https://github.com/angular/angular/issues/53485) is the one to watch.

**Comment by RobbyRabbitman** [comment]
So, should ngxtension create a signal based api or not? :D

**Comment by eneajaho** [comment]
> So, should ngxtension create a signal based api or not? :D

Probably not, let's leave that part to the framework 😅

**Comment by eneajaho** [comment]
Closing this issue as the PR that makes ngControl public was merged 🙌
