### ISSUE TITLE
Is there any way to perform reset to initial state in signal slice?

### ISSUE THREAD

**Issue by illunix** [ngxtension/ngxtension-platform#496]
Is there any way to perform reset to initial state in signal slice or I need to add this code to every state?
```ts
 resetToInitialState: (_, $: Observable<void>) =>
        $.pipe(map(() => signInInitialState))
```

**Comment by joshuamorony** [comment]
@illunix no there is no default reset action source, what you have suggested would be an appropriate way to go about it
