### ISSUE TITLE
Queries Migration should automatically add non-null assertion for non-nullable view-child members

### ISSUE THREAD

**Issue by ShacharHarshuv** [ngxtension/ngxtension-platform#498]
I believe the [Queries Migration](https://ngxtension.netlify.app/utilities/migrations/queries-migration/) should be changed to automatically add non-null assertion to calls. 

Imagine this "old" code:
```ts
  @ViewChild(MyComponent) myComponent: MyComponent;
```

It's type is not undefined, however, it would be undefined in runtime if we are trying to read the value before view init, or if the child does not exist. 

After migration

```ts
myComponent = viewChild(MyComponent);
```

Angular cleverly makes the inferred type here to be `Signal<MyComponent | undefined>`. (See [here for more details](https://angular.dev/guide/signals/queries#results-availability-timing)).

That means, however, that a consumer that did not handle the option of `undefined` will now break. (And indeed, it's very possible that they did not handle it if the member was not typed as optional or `undefined`able. That is the reason why **I think that in this situation non-null assertion should be added to usages**. 

However, I think we can avoid the non-null assertion in case that the member was typed property, like here:

```ts
  @ViewChild(MyComponent) myComponent?: MyComponent;
```

I noticed in the code that you add non-null assertions for accessing inside an if statement body (where it would otherwise be inferred). I think that logic should be used only if the original member was nullable / undefineable, and otherwise we should just always add the non-null assertion.

**Comment by eneajaho** [comment]
Hello @ShacharHarshuv 
We will deprecate these migrations and recommend going with the official ones that Angular will release https://github.com/angular/angular/pull/57525

So for the moment, these things are freezed.

**Comment by eneajaho** [comment]
Yeah, signal inputs, outputs, signal queries, will all be handled by Angular migrations at some point.
