### ISSUE TITLE
[feature request] Enhance createNotifier to support optional initialization at value 1

### ISSUE THREAD

**Issue by endlacer** [ngxtension/ngxtension-platform#505]
## Feature Request: Optional Initialization Value for createNotifier

Currently, the `createNotifier` function in our utility library initializes the `sourceSignal` with a value of 0. This works well for many use cases, but there's an opportunity to improve its flexibility and immediate usability in certain scenarios.

### Proposed Enhancement

Modify the `createNotifier` function to accept an optional parameter that allows initializing the `sourceSignal` with a value of 1 instead of 0.

### Rationale

1. **Immediate Computation**: When a computed signal is listening to this notifier, initializing with 1 would trigger immediate computation. This can be beneficial in scenarios where we want the computed signal to evaluate right away without waiting for the first `notify` call.

2. **Flexibility**: Providing this option increases the versatility of the `createNotifier` function, allowing developers to choose the initialization behavior that best suits their specific use case.

### Suggested Implementation

```typescript
import { signal } from '@angular/core';

export function createNotifier(startAtOne: boolean = false) {
  const sourceSignal = signal(startAtOne ? 1 : 0);

  return {
    notify: () => {
      sourceSignal.update((v) => (v >>> 0) + 1);
    },
    listen: sourceSignal.asReadonly(),
  };
}
```

### Benefits

1. Backwards compatible: Existing usage remains unchanged.
2. Improved developer experience: Offers more control over initial behavior.
3. Potential performance optimization: Eliminates the need for an immediate `notify` call in some scenarios.

### Questions for Discussion

1. Should we consider other initial values beyond 0 and 1?
2. Are there any potential drawbacks or edge cases we should be aware of?

Your thoughts and feedback on this enhancement are welcome!

**Comment by eneajaho** [comment]
Hello @endlacer 
I'd like to see how this pattern is being used. Because most of the time, I just call the listen() fn and that's it. And if I need to wait for the initial change to happen, that's when I wrap the code with it: ex:
```ts
if (notifier.listen()) {
 // logic to run after the initial run
}
```

**Comment by endlacer** [comment]
@eneajaho mh yeah you absolutely right. I, for whatever reason, always wrapped it in a if-statement. I could've just called it.. can be closed 🫣
