### ISSUE TITLE
new function for signal/rxjs interop

### ISSUE THREAD

**Issue by ymajoros** [ngxtension/ngxtension-platform#507]
Crossposting from a feature request I created in Angular. It might actually be useful here, if it doesn't move in angular/core.

### Description

I propose some function to run some computation that returns an Observable, and convert it to a signal, in a way similar to compute(), with all its goodies and without additional steps.

Typical workflow:
- inputs = signals
- when they change, run some computation (typically, http requests)
- convert to a signal

### Proposed solution

```typescript
export function computedFromObservable<T>(computation: () => Observable<T>, options?: CreateComputedOptions<Observable<T>>): Signal<T | undefined> {
  const computedSignal = computed(computation, options);
  const computedObservable = toObservable(computedSignal);
  const observable = computedObservable.pipe(
    switchAll()
  );
  return toSignal(observable);
}
```

which can be used this way:
```typescript
    this.productPage = computedFromObservable(() => this.productService.find$(this.productSearch(), this.pagination()));
```

... replacing this more complicated construct:
```typescript
    const productParams: Signal<[ProductSearch, Pagination]> = computed(() => [this.preparationSearch(), this.pagination()]);
    const productPageObservable = toObservable(productParams).pipe(
      switchMap(([productSearch, pagination]) => this.productService.find$(productSearch, pagination))
    );
    this.productPage = toSignal(productPageObservable);
```

### Alternatives considered

Originally, I something like this, but it lacked the power of `computed()` (single signal as input often requiring to create an additional computed() signal anyway, not as lazy, ...):
```typescript
export function pipeSignalWithDefault<T, U>(signal: Signal<T>, pipe: OperatorFunction<T, U>, initialValue: U): Signal<U> {
  const signalAsObservable = toObservable(signal);
  const signalPipe = signalAsObservable.pipe(pipe);

  return toSignal(signalPipe, {initialValue});
}
```
(+ ngxtension utility functions).

Similar Angular feature request: https://github.com/angular/angular/issues/57946

**Comment by eneajaho** [comment]
How is this different from: https://ngxtension.netlify.app/utilities/signals/derived-async/ and https://ngxtension.netlify.app/utilities/signals/derived-from/ ?

**Comment by ymajoros** [comment]
@eneajaho Well, maybe it's just that :smile: (at least `derivedAsync`).

Lots of people seem to write about combining rxjs and signals, but I couldn't find these help functions until today (with the related blog post presenting the history of the lib).

Is there any talk with the Angular team to migrate some of the functionality to Angular itself? It seems not only useful, but about a core functionalities to be able to work with signals and rxjs.

**Comment by eneajaho** [comment]
I don't know if it will reach the fwk, but if you don't want to install a library, you can just copy the function in your codebase as it's only one file.

Closing this issue as it's already resolved.

**Comment by ymajoros** [comment]
I'm ok installing a library, of course. I just didn't know it had that functionality, glad to hear.
