### ISSUE TITLE
Add possibility to compute a new selector from other selectors in signalSlice

### ISSUE THREAD

**Issue by alaindeurveilher** [ngxtension/ngxtension-platform#518]
SignalSlice is great. I can create selectors to derive from the intial state, such as:

```ts
myState = signalSlice({
  // ...
  selectors: (state) => ({
    sortedItems: () => sortBy(state().items(), (item) => item.order),
  }),
});
```

But what if I want a state that derives from one of the selectors? something like:

```ts
myState = signalSlice({
  // ...
  selectors: (state) => ({
    sortedItems: () => sortBy(state().items(), (item) => item.order),
    isEmpty: () => state().sortedItems.length === 0, // sortedItems does not exist on state()
  }),
});
```

At the moment this does not work, as sortedItems does not exist on the state param.
Do you think this is something that could be done, without falling into some infinite loop ?

Thank you.

**Comment by joshuamorony** [comment]
Hi @alaindeurveilher, there is a way you can achieve this, check this issue for details: https://github.com/ngxtension/ngxtension-platform/issues/187

**Comment by alaindeurveilher** [comment]
That was it. Thank you very much @joshuamorony !
