### ISSUE TITLE
SignalSlice Type doesn't match the return object.

### ISSUE THREAD

**Issue by LukeEdgecock-Bennett** [ngxtension/ngxtension-platform#520]
can we please add   InitialStateStreams<TSignalValue>  to the type definition for SignalSlice? 

I spent a while trying to figure out why I couldn't see the initial values streams on my state object until I realised that it was missing from the type definition. 

@joshuamorony is it intended to be missing at the current stage?

**Comment by joshuamorony** [comment]
Thanks @LukeEdgecock-Bennett I've put up a PR for this
