### ISSUE TITLE
ngxtension:convert-outputs does not work for EventEmitters with types

### ISSUE THREAD

**Issue by BeGj** [ngxtension/ngxtension-platform#527]
Problem:
convert-outputs migration does not support EventEmitters that are typed with objects(?).

If a component has an output defined such as 
´´´
@Output()
createOrUpdateDtoOutput = new EventEmitter<{
id: string;
dto: CreateOrUpdateDto;
}>();
´´´

it will end up as
´´´
createOrUpdateDtoOutput = output();
´´´
and later in the code when stuff calls .next() it is not changed to .emit(), and Angular will also complain in all parent components about that output `Argument of type 'void' is not assignable to paramter of type '{dto: {....}}; id: string;}'`

**Comment by eneajaho** [comment]
Hello @BeGj 
I'd recommend to try using the official Angular migrations 

https://angular.dev/reference/migrations/outputs

The version we have on ngxntesion will be deprecated soon, as the official one is better and supports more usecases and patterns.

**Comment by eneajaho** [comment]
Closing as not planned.
